default: &default
  store_options:
    max_age: <%= 1.week.to_i %>
    max_size: <%= 256.megabytes %>
    namespace: <%= Rails.env %>

development:
  <<: *default
  database: recruit_development

test:
  <<: *default
  database: recruit_test

production:
  <<: *default
  database: recruit_production
